
#include "CppUTest/TestHarness.h"
#include "CppUTestExt/MockSupport.h"

#include "wx/listbase.h"

DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_COL_CLICK);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_ITEM_ACTIVATED);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_COL_DRAGGING);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_END_LABEL_EDIT);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_BEGIN_LABEL_EDIT);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_BEGIN_DRAG);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_ITEM_SELECTED);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_COL_RIGHT_CLICK);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_COL_END_DRAG);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_ITEM_DESELECTED);
DEFINE_EVENT_TYPE(wxEVT_COMMAND_LIST_ITEM_FOCUSED);

wxClassInfo *wxListEvent::GetClassInfo() const
{
	FAIL("wxListEvent::GetClassInfo");
	return NULL;
}

wxClassInfo *wxListItem::GetClassInfo() const
{
	FAIL("wxListItem::GetClassInfo");
	return NULL;
}

