.TH fzdefaults.xml 5 "January 2008" "" "FileZilla Manual"
.SH NAME
fzdefaults.xml \- Default options for FileZilla
.SH SYNOPSIS
.B /etc/filezillafzdefaults.xml
.br
.B  ~/.filezilla/fzdefaults.xml
.SH DESCRIPTION
This configuration file can be used to specify some system-wide default options for FileZilla:
.IP \(bu (bullet)
Location of user's settings directory
.IP \(bu (bullet)
Predefined list of Sitemanager entries
.P
Please search for the file
.B fzdefaults.xml.example
for further information. It is often found in the /usr/share/filezilla/docs directory.
.SH SUPPORT
Please visit http://filezilla-project.org/ for further information. Report bugs only if you are using the latest version available from the FileZilla website.
.SH COPYRIGHT
Copyright (C) 2004-2008  Tim Kosse
.P
FileZilla is distributed under the terms of the GNU General Public License version 2 or later.
.SH "SEE ALSO"
filezilla(1)
