.TH fzsftp 1 "January 2008" "" "FileZilla Manual"
.SH NAME
fzsftp \- SFTP connection handler of FileZilla
.SH SYNOPSIS
.B filezilla
.SH DESCRIPTION
.B fzsftp
is part of FileZilla. It is used to handle SFTP (SSH File Transfer Protocol) connections. It usually gets called by FileZilla and is not intended to be used directly.
.P
.B fzsftp
is based on the psftp component of PuTTY
.SH SUPPORT
Please visit http://filezilla-project.org/ for further information. Report bugs only if you are using the latest version available from the FileZilla website.
.SH COPYRIGHT
Copyright (C) 2004-2008  Tim Kosse
.br
Copyright (C) 1997-2008  Simon Tatham and the PuTTY team
.P
FileZilla is distributed under the terms of the GNU General Public License version 2 or later.
.SH "SEE ALSO"
filezilla(1)
